const URL='https://fosrixbjwmusfocckqaq.supabase.co',KEY='sb_publishable_ASBrww5alY6wsWc_H8_1jA_T5hG5-rb',sb=supabase.createClient(URL,KEY);let applications=[],selected=null;
const $=id=>document.getElementById(id),login=$('login'),app=$('app');
async function boot(){const {data:{session}}=await sb.auth.getSession();if(session)await enter(session);else showLogin()}
function showLogin(){login.hidden=false;app.hidden=true}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='Signing in…';const {data,error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent='Sign in failed. Check your email and password.';return}await enter(data.session)}
async function enter(session){const {data:admin}=await sb.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(!admin){await sb.auth.signOut();$('loginMsg').textContent='This account is not authorised for the Ajo back office.';showLogin();return}login.hidden=true;app.hidden=false;await loadApps();await loadTestimonials()}
$('logout').onclick=async()=>{await sb.auth.signOut();showLogin()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));
function switchTab(id){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$('pageTitle').textContent={dashboard:'Dashboard',applications:'Applications',groups:'Ajo Groups',testimonials:'Testimonials'}[id]}
async function loadApps(){const {data,error}=await sb.from('applications').select('*').order('created_at',{ascending:false});if(error)return;applications=data||[];renderStats();renderRows();renderRecent()}
function renderStats(){const c=s=>applications.filter(a=>a.status===s).length,n=c('new');$('sNew').textContent=n;$('sApproved').textContent=c('confirmed');$('sWait').textContent=c('waitlisted');$('sTotal').textContent=applications.length;if($('newDot'))$('newDot').style.display=n?'inline':'none';document.title=n?'('+n+') New Ajo Applications · Back Office':'Ajo 2.0 Admin'}
function name(a){return esc(a.full_name||'Applicant')}function product(a){return esc(a.product_name||a.goal_type||'Goal-based Ajo')}
function renderRecent(){$('recent').innerHTML=applications.slice(0,5).map(a=>'<div class="testimonial"><b>'+name(a)+'</b> · '+product(a)+' <span class="status '+a.status+'">'+a.status+'</span><br><small>Preferred position: '+(a.preferred_position||'Any')+'</small> <button class="linkbtn" onclick="openApp(\''+a.id+'\')">View</button></div>').join('')||'<p>No applications yet.</p>'}
function renderRows(){let q=$('search').value.toLowerCase(),f=$('filter').value;let list=applications.filter(a=>(!f||a.status===f)&&(!q||[a.full_name,a.phone,a.product_name,a.goal_type].some(x=>(x||'').toLowerCase().includes(q))));$('appRows').innerHTML=list.map(a=>'<tr><td><b>'+name(a)+'</b><br><small>'+esc(a.phone||'')+'</small></td><td>'+product(a)+'</td><td>'+(a.preferred_position||'Any')+'</td><td><span class="status '+a.status+'">'+a.status+'</span></td><td><button class="linkbtn" onclick="openApp(\''+a.id+'\')">Manage</button></td></tr>').join('')}
$('search').oninput=renderRows;$('filter').onchange=renderRows;
window.openApp=id=>{selected=applications.find(a=>a.id===id);if(!selected)return;$('drawerContent').innerHTML='<small>APPLICATION</small><h2>'+name(selected)+'</h2><div class="detailgrid">'+D('Reference',selected.application_reference)+D('Phone',selected.phone)+D('Email',selected.email)+D('Ajo',selected.product_name||selected.goal_type)+D('Monthly contribution',money(selected.contribution_amount))+D('Preferred position',selected.preferred_position||'No preference')+D('Goal due date',fmt(selected.goal_due_date))+D('Verification',selected.verification_status)+D('Status',selected.status)+D('WhatsApp invite',selected.whatsapp_invite_url||'Not added')+'</div><label>WhatsApp group invite URL<input id="whatsappInvite" type="url" value="'+esc(selected.whatsapp_invite_url||'')+'" placeholder="Paste the approved group invite link"></label><label>Admin notes<textarea id="adminNotes" rows="4">'+esc(selected.admin_notes||'')+'</textarea></label><label>Verification<select id="verificationEdit"><option value="not_started">Not started</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="failed">Failed</option></select></label><label>Status<select id="statusEdit">'+['new','review','offer_sent','accepted','confirmed','waitlisted','rejected'].map(s=>'<option '+(s===selected.status?'selected':'')+'>'+s+'</option>').join('')+'</select></label><div class="actions"><button class="approve" onclick="saveApp()">Save changes</button><button onclick="quickStatus(\'offer_sent\')">Offer sent</button><button onclick="quickStatus(\'confirmed\')">Confirm member</button><button onclick="quickStatus(\'waitlisted\')">Waitlist</button><button class="reject" onclick="quickStatus(\'rejected\')">Reject</button></div>';const digits=String(selected.phone||'').replace(/\D/g,'').replace(/^0/,'234');const msg='Hi '+(selected.full_name||'')+' 👋🏾%0A%0AGood news! Your Ajo 2.0 application has been reviewed.%0A%0AReference: '+(selected.application_reference||'')+'%0AAjo: '+(selected.product_name||selected.goal_type||'Ajo 2.0')+'%0APreferred position: '+(selected.preferred_position?'Position '+selected.preferred_position:'No preference')+'%0A%0APlease use your application reference and phone number on the Ajo 2.0 website to check your latest status and next steps.';$('drawerContent').innerHTML+='<p><a class="approve" style="display:inline-block;text-decoration:none;padding:12px 16px;border-radius:10px" target="_blank" rel="noopener" href="https://wa.me/'+digits+'?text='+msg+'">Send status update on WhatsApp</a></p>';$('drawer').hidden=false;setTimeout(()=>{if($('verificationEdit'))$('verificationEdit').value=selected.verification_status||'not_started'},0)};
window.saveApp=async()=>{await updateApp($('statusEdit').value,$('adminNotes').value,$('verificationEdit').value)};window.quickStatus=async s=>{await updateApp(s,$('adminNotes').value,$('verificationEdit')?.value||selected.verification_status)};
async function updateApp(status,admin_notes,verification_status){let patch={status,admin_notes:admin_notes||null,verification_status,whatsapp_invite_url:$('whatsappInvite')?.value.trim()||null};if(status==='offer_sent')patch.offer_sent_at=new Date().toISOString();if(status==='accepted')patch.accepted_at=new Date().toISOString();if(status==='confirmed')patch.confirmed_at=new Date().toISOString();const {error}=await sb.from('applications').update(patch).eq('id',selected.id);if(!error){$('drawer').hidden=true;await loadApps()}}
$('closeDrawer').onclick=()=>{$('drawer').hidden=true};
$('newGroup').onclick=()=>{showModal('<small>NEW AJO GROUP</small><h2>Create a group</h2><form id="groupForm"><label>Group code<input name="code" placeholder="BG-01" required></label><label>Product<select name="product"><option>Small Small</option><option>Easy Ajo</option><option>Goal Ajo</option><option>Big Goal Ajo</option><option>Premium Ajo</option></select></label><div class="detailgrid"><label>Contribution<input name="contribution" type="number" required></label><label>Service fee<input name="fee" type="number" required></label></div><label>Cycle start<input name="start" type="date" required></label><button>Create group</button></form>');$('groupForm').onsubmit=createGroup};
async function createGroup(e){e.preventDefault();let f=new FormData(e.target);const {error}=await sb.from('ajo_groups').insert({group_code:f.get('code'),product_name:f.get('product'),contribution_amount:Number(f.get('contribution')),service_fee:Number(f.get('fee')),cycle_start:f.get('start')});if(!error){$('modal').hidden=true;alert('Group created. Position setup is the next step.');}}
$('addTestimonial').onclick=()=>{showModal('<small>MEMBER STORY</small><h2>Add testimonial</h2><form id="testForm"><label>Display name<input name="name" required></label><label>Quote<textarea name="quote" rows="4" required></textarea></label><label>Ajo/product<input name="product"></label><label>Cycle label<input name="cycle" placeholder="Cycle 1"></label><label><input style="width:auto" name="permission" type="checkbox" required> Member gave permission to publish</label><label><input style="width:auto" name="published" type="checkbox"> Publish now</label><button>Add testimonial</button></form>');$('testForm').onsubmit=createTestimonial};
async function createTestimonial(e){e.preventDefault();let f=new FormData(e.target);const {error}=await sb.from('testimonials').insert({display_name:f.get('name'),quote:f.get('quote'),product_name:f.get('product')||null,cycle_label:f.get('cycle')||null,permission_confirmed:f.get('permission')==='on',published:f.get('published')==='on'});if(!error){$('modal').hidden=true;await loadTestimonials()}}
async function loadTestimonials(){const {data}=await sb.from('testimonials').select('*').order('created_at',{ascending:false});$('testimonialList').innerHTML=(data||[]).map(t=>'<div class="testimonial"><p>“'+esc(t.quote)+'”</p><b>'+esc(t.display_name)+'</b> <small>'+esc(t.product_name||'')+' · '+(t.published?'Published':'Not published')+'</small></div>').join('')||'<p>No testimonials added yet.</p>'}
function showModal(x){$('modalContent').innerHTML=x;$('modal').hidden=false}$('closeModal').onclick=()=>{$('modal').hidden=true};
function D(k,v){return '<div class="detail"><small>'+k+'</small><b>'+esc(v||'—')+'</b></div>'}function money(v){return v?'₦'+Number(v).toLocaleString():'—'}function fmt(v){if(!v)return'—';return new Date(v+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}boot();