const ENDPOINT='https://fosrixbjwmusfocckqaq.supabase.co/functions/v1/owner-approval',$=id=>document.getElementById(id);let pin=sessionStorage.getItem('ajoo_owner_pin')||'',apps=[],groups=[],positions=[],current=null,selectedGroup=null,selectedPos=null;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=n=>'₦'+Number(n||0).toLocaleString('en-NG'),month=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-GB',{month:'short',year:'numeric'}):'—';
async function api(body){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin})}),d=await r.json().catch(()=>({error:'Server error'}));if(!r.ok)throw Error(d.error||'Request failed');return d}function showLogin(){$('login').hidden=false;$('app').hidden=true}function showApp(){$('login').hidden=true;$('app').hidden=false}
$('loginForm').onsubmit=async e=>{e.preventDefault();pin=$('ownerPin').value;$('loginMsg').textContent='Checking…';try{await api({action:'login'});sessionStorage.setItem('ajoo_owner_pin',pin);showApp();await load()}catch(e){$('loginMsg').className='msg error';$('loginMsg').textContent=e.message}};$('logout').onclick=()=>{pin='';sessionStorage.removeItem('ajoo_owner_pin');showLogin()};$('refresh').onclick=load;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab)});
async function load(){try{const d=await api({action:'list'});apps=d.applications||[];groups=d.groups||[];positions=d.positions||[];renderAll()}catch(e){showLogin();$('loginMsg').textContent=e.message}}
function appCard(a){return '<article class="card"><div><span class="pill '+esc(a.status)+'">'+esc(a.status.replaceAll('_',' '))+'</span><h3>'+esc(a.full_name)+'</h3><div class="meta">'+esc(a.application_reference)+' · '+esc(a.phone)+'</div></div><div><div class="meta">Ajoo</div><b>'+money(a.contribution_amount)+'/month</b></div><div><div class="meta">Requested turn</div><div class="month">Position '+esc(a.preferred_position)+' · '+month(a.collection_date)+'</div><div class="meta">'+esc(a.group_code||'')+'</div></div><button class="ghost reviewBtn" data-ref="'+esc(a.application_reference)+'">Review</button></article>'}
function renderAll(){const pending=apps.filter(a=>['review','new','offer_sent'].includes(a.status));$('pendingCount').textContent=pending.length;$('confirmedCount').textContent=apps.filter(a=>a.status==='confirmed').length;$('availableCount').textContent=positions.filter(p=>p.status==='available').length;$('groupCount').textContent=groups.filter(g=>g.status==='forming').length;$('attention').innerHTML=pending.slice(0,6).map(appCard).join('')||'<p class="empty">Nothing waiting for review.</p>';renderApps();renderGroups();bindReview()}
function renderApps(){const q=$('search').value.toLowerCase(),f=$('filter').value,list=apps.filter(a=>(!f||a.status===f)&&(!q||[a.full_name,a.phone,a.application_reference].some(v=>String(v||'').toLowerCase().includes(q))));$('queue').innerHTML=list.map(appCard).join('')||'<p class="empty">No matching applications.</p>';bindReview()}$('search').oninput=renderApps;$('filter').onchange=renderApps;
function renderGroups(){$('groupGrid').innerHTML=groups.map(g=>{const ps=positions.filter(p=>p.group_id===g.id).sort((a,b)=>a.position_number-b.position_number);return '<article class="group-card"><div class="group-head"><div><h3>'+money(g.contribution_amount)+' Ajoo · '+esc(g.group_code)+'</h3><div class="meta">Service fee '+money(g.service_fee)+'/month · '+esc(g.status)+'</div></div><b>'+ps.filter(p=>p.status==='confirmed').length+'/5 filled</b></div><div class="five">'+ps.map(p=>{const a=apps.find(x=>x.application_reference&&x.assigned_group_id===g.id&&x.assigned_position===p.position_number);return '<div class="slot '+esc(p.status)+'"><b>Position '+p.position_number+'</b><span>'+month(p.collection_date)+'</span><span>'+(a?esc(a.full_name):p.status==='available'?'Available':'Confirmed')+'</span></div>'}).join('')+'</div></article>'}).join('')}
function bindReview(){document.querySelectorAll('.reviewBtn').forEach(b=>b.onclick=()=>openReview(b.dataset.ref))}
function openReview(ref){current=apps.find(a=>a.application_reference===ref);if(!current)return;selectedGroup=current.requested_group_id;selectedPos=current.preferred_position;$('dName').textContent=current.full_name;$('adminNote').value=current.admin_notes||'';$('waInvite').value='';['checkPhone','checkDetails','checkRules'].forEach(id=>$(id).checked=false);$('actionMsg').textContent='';$('dDetails').innerHTML=[['Reference',current.application_reference],['Phone',current.phone],['Email',current.email||'—'],['Ajoo',money(current.contribution_amount)+'/month'],['Requested','Position '+current.preferred_position+' · '+month(current.collection_date)],['Status',current.status],['Referral',current.referral_code||'—'],['Applicant note',current.notes||'—']].map(([k,v])=>'<div><span class="meta">'+esc(k)+'</span><b>'+esc(v)+'</b></div>').join('');renderReviewPositions();$('reviewDialog').showModal()}
function renderReviewPositions(){const gs=groups.filter(g=>Number(g.contribution_amount)===Number(current.contribution_amount)&&g.status==='forming'),box=$('reviewPositions');box.innerHTML=gs.flatMap(g=>positions.filter(p=>p.group_id===g.id).sort((a,b)=>a.position_number-b.position_number).map(p=>'<button type="button" class="review-slot '+(selectedGroup===g.id&&selectedPos===p.position_number?'selected':'')+'" data-g="'+g.id+'" data-p="'+p.position_number+'" '+(p.status!=='available'?'disabled':'')+'><b>P'+p.position_number+'</b><br><small>'+month(p.collection_date)+' · '+(p.status==='available'?'Available':'Taken')+'</small></button>')).join('');box.querySelectorAll('.review-slot:not(:disabled)').forEach(b=>b.onclick=()=>{selectedGroup=b.dataset.g;selectedPos=Number(b.dataset.p);renderReviewPositions()})}
$('closeDialog').onclick=()=>$('reviewDialog').close();
async function decide(decision){if(!current)return;if(decision==='approve'&&!['checkPhone','checkDetails','checkRules'].every(id=>$(id).checked)){$('actionMsg').className='msg error';$('actionMsg').textContent='Complete all three verification checks before approval.';return}if(['reject','waitlist'].includes(decision)&&!confirm('Continue with '+decision+'?'))return;$('actionMsg').className='msg';$('actionMsg').textContent='Updating…';try{await api({action:'review',reference:current.application_reference,decision,group_id:selectedGroup,position:selectedPos,admin_note:$('adminNote').value,whatsapp_invite_url:$('waInvite').value});$('actionMsg').className='msg success';$('actionMsg').textContent=decision==='approve'?'Approved. Position confirmed.':decision==='offer'?'Alternative position recorded as offered.':'Application updated.';setTimeout(async()=>{$('reviewDialog').close();await load()},650)}catch(e){$('actionMsg').className='msg error';$('actionMsg').textContent=e.message}}
$('approve').onclick=()=>decide('approve');$('offer').onclick=()=>decide('offer');$('waitlist').onclick=()=>decide('waitlist');$('reject').onclick=()=>decide('reject');(async()=>{if(pin){try{await api({action:'login'});showApp();await load();return}catch{pin='';sessionStorage.removeItem('ajoo_owner_pin')}}showLogin()})();