const URL='https://fosrixbjwmusfocckqaq.supabase.co',KEY='sb_publishable_ASBrww5alY6wsWc_H8_1jA_T5hG5-rb',sb=supabase.createClient(URL,KEY);const $=id=>document.getElementById(id);let apps=[],current=null;
const money=n=>n==null?'—':'₦'+Number(n).toLocaleString('en-NG');const month=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-GB',{month:'long',year:'numeric'}):'—';const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function showLogin(){$('login').hidden=false;$('app').hidden=true}function showApp(){$('login').hidden=true;$('app').hidden=false}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='Signing in…';const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').className='msg error';$('loginMsg').textContent='Sign in failed: '+error.message;return}await enter(data.session)};
async function enter(session){const {data:admin,error}=await sb.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!admin){await sb.auth.signOut();$('loginMsg').className='msg error';$('loginMsg').textContent='This account is not authorised for the Approval Centre.';showLogin();return}$('adminEmail').textContent=session.user.email;showApp();await load()}
$('logout').onclick=async()=>{await sb.auth.signOut();showLogin()};$('refresh').onclick=load;$('search').oninput=render;$('filter').onchange=render;
async function load(){const {data,error}=await sb.rpc('admin_application_queue');if(error){$('queue').innerHTML='<p class="msg error">Could not load applications: '+esc(error.message)+'</p>';return}apps=data||[];render()}
function render(){const q=$('search').value.toLowerCase(),f=$('filter').value;const list=apps.filter(a=>(!f||a.status===f)&&(!q||[a.full_name,a.phone,a.application_reference,a.product_name].some(v=>String(v||'').toLowerCase().includes(q))));$('reviewCount').textContent=apps.filter(a=>a.status==='review').length;$('confirmedCount').textContent=apps.filter(a=>a.status==='confirmed').length;$('waitCount').textContent=apps.filter(a=>a.status==='waitlisted').length;$('totalCount').textContent=apps.length;$('empty').hidden=!!list.length;$('queue').innerHTML=list.map(a=>'<article class="card"><div><span class="pill '+esc(a.status)+'">'+esc(a.status.replace('_',' '))+'</span><h3>'+esc(a.full_name)+'</h3><div class="meta">'+esc(a.application_reference)+' · '+esc(a.phone)+'</div></div><div><div class="meta">Ajo</div><b>'+esc(a.product_name||'Goal-based Ajo')+'</b><div class="meta">'+money(a.contribution_amount)+'/month</div></div><div><div class="meta">Collection turn</div><div class="month">Position '+esc(a.preferred_position)+' · '+month(a.collection_date)+'</div><div class="meta">'+esc(a.group_code||'')+'</div></div><button class="ghost" data-ref="'+esc(a.application_reference)+'">Review</button></article>').join('');document.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>openReview(b.dataset.ref))}
function openReview(ref){current=apps.find(a=>a.application_reference===ref);if(!current)return;$('dName').textContent=current.full_name;$('adminNote').value=current.admin_notes||'';$('waInvite').value='';$('actionMsg').textContent='';$('dDetails').innerHTML=[['Reference',current.application_reference],['Status',current.status],['Phone',current.phone],['Email',current.email||'—'],['Ajo',current.product_name||'Goal-based Ajo'],['Contribution',money(current.contribution_amount)],['Position','Position '+current.preferred_position],['Collection month',month(current.collection_date)],['Group',current.group_code||'—'],['Verification',current.verification_status],['Goal',current.goal_type||'—'],['Target',money(current.target_amount)],['Applied',new Date(current.created_at).toLocaleString('en-GB')],['Applicant note',current.notes||'—']].map(([k,v])=>'<div><span class="meta">'+esc(k)+'</span><b>'+esc(v)+'</b></div>').join('');$('reviewDialog').showModal()}
async function act(action){if(!current)return;if((action==='reject'||action==='waitlist')&&!confirm((action==='reject'?'Reject':'Waitlist')+' this application and release Position '+current.preferred_position+'?'))return;$('actionMsg').className='msg';$('actionMsg').textContent='Updating…';const {error}=await sb.rpc('admin_review_application',{p_reference:current.application_reference,p_action:action,p_admin_notes:$('adminNote').value,p_whatsapp_invite_url:$('waInvite').value});if(error){$('actionMsg').className='msg error';$('actionMsg').textContent=error.message;return}$('actionMsg').className='msg success';$('actionMsg').textContent=action==='approve'?'Approved. Position confirmed.':'Updated. Position released.';setTimeout(async()=>{$('reviewDialog').close();await load()},700)}
$('approve').onclick=()=>act('approve');$('waitlist').onclick=()=>act('waitlist');$('reject').onclick=()=>act('reject');
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session)await enter(session);else showLogin()})();